package com.springboot.springboot_soap_service.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;
import org.springframework.ws.client.core.WebServiceTemplate;

@Configuration
public class SoapClientConfig {

    // Inject the SOAP endpoint URL from the application properties file
    @Value("${soap.endpoint}")
    private String soapEndpoint;

    /**
     * Bean for Jaxb2Marshaller to convert Java objects to XML and vice versa.
     * We set the package to scan which contains the generated classes (e.g., Add, AddResponse)
     * that were generated by the wsimport tool.
     *
     * @return Jaxb2Marshaller
     */
    @Bean
    public Jaxb2Marshaller marshaller() {
        Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
        // Set the package where the generated JAXB classes are located
        marshaller.setPackagesToScan("com.example.soap.generated.calculator");
        return marshaller;
    }

    /**
     * Bean for WebServiceTemplate that uses the Jaxb2Marshaller to marshal/unmarshal requests/responses.
     * The WebServiceTemplate is used to interact with the SOAP service by sending requests and receiving responses.
     * We also set the default URI for the SOAP endpoint, which is the base URL of the SOAP service.
     *
     * @param marshaller Jaxb2Marshaller for request and response conversion
     * @return WebServiceTemplate
     */
    @Bean
    public WebServiceTemplate webServiceTemplate(Jaxb2Marshaller marshaller) {
        WebServiceTemplate webServiceTemplate = new WebServiceTemplate();

        // Set the marshaller and unmarshaller to handle SOAP message conversion
        webServiceTemplate.setMarshaller(marshaller);
        webServiceTemplate.setUnmarshaller(marshaller);

        // Set the default SOAP service endpoint URI
        webServiceTemplate.setDefaultUri(soapEndpoint);
        return webServiceTemplate;
    }
}
